version: "2"
services:
  haproxy:
    image: haproxy
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  app1:
    image: test
    environment: 
      - MONGO_HOST=db
      - SERVER_NAME=app1
      - PORT=3000
    depends_on:
      - db  
  db:
    image: mongo
    volumes:
       - ./db:/data/db
  

    
