version: "2"
services:
  haproxy:
    image: haproxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/haproxy/certs/:/etc/haproxy/certs/
  app1:
    image: test
    environment: 
      - MONGO_HOST=db
      - SERVER_NAME=app1
      - PORT=3000
    depends_on:
      - db  
  db:
    image: mongo
    volumes:
       - ./db:/data/db
  

    
